### ISSUE TITLE
Proxy support for rest and websocket

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/megalodon#69]
Some countries are blocked from some server, so user could not connect the server directly. The user have to use proxy server.

refs: https://github.com/h3poteto/whalebird-desktop/issues/982

### TODO
- [x] REST API
- [x] Streaming
- [x] WebSocket

### Checklist
- [x] Connect to https mastodon server through http proxy without authentication
- [x] Connect to https pleroma server through http proxy without authentication
- [x] Connect to https mastodon server through socks proxy without authentication
- [x] Connect to https pleroma server through socks proxy without authentication

**Comment by h3poteto** [comment]
For REST: axios can request with proxy: https://github.com/axios/axios#request-config
For Websocket: ws can connection with proxy: https://github.com/websockets/ws#how-to-connect-via-a-proxy
but I have to use another `http.Agent` like https-proxy-agent: https://github.com/TooTallNate/node-https-proxy-agent#ws-websocket-connection-example

**Comment by dpwiz** [comment]
Not only some countries, but lots of companies too require connecting to external networks via proxy for "security".
